### ISSUE TITLE
About mobile device

### ISSUE THREAD

**Issue by TwT520Ly** [YuliangXiu/MobilePose-pytorch#10]
Can i use python to implement the post processing stage of the pose estimate ? And then use tensorflow to save it to .pb file.And then only use a little interface in java to load the model and give input ,directly get the output Image

**Comment by YuliangXiu** [comment]
I do not think so, the pb file can only save trained model but not post-processing operation. You need to reimplement it by Jave(Android) or Swift(iOS), which is also the case in pre-processing (e.g. rescale/wrap operation on original image before throwing into model).
