### ISSUE TITLE
inference accuracy poor

### ISSUE THREAD

**Issue by sysau** [YuliangXiu/MobilePose-pytorch#13]
hi, yuliang, I test the resnet model, but got very poor accuracy
![pose](https://user-images.githubusercontent.com/23167943/42493604-4112ccda-8450-11e8-9b1e-01173be41f3a.jpg)

original input is:
![p12](https://user-images.githubusercontent.com/23167943/42493746-c31c6c04-8450-11e8-8fa0-44f8bfb723a8.jpg)

**Comment by YuliangXiu** [comment]
Yes, this version is only a beta version. We are working on a more accurate version.
