### ISSUE TITLE
_make.so cannot be reproduced

### ISSUE THREAD

**Issue by ba-san** [YuliangXiu/MobilePose-pytorch#20]
Hi, @Fangyh09 

On the process to deploy this mobilepose for mobile use (raspberry pi), I realized _make.so at MobilePose-pytorch/cocoapi/PythonAPI/pycocotools/  is 64bit file.
I need to get 32bit version to run on it.

So, I tried to create 32bit _mask.so, but when I use it, I get following error.

>daisuke@daisuke-Z170X-UD3:~/MobilePose-pytorch$ python eval_psl.py 
> Traceback (most recent call last):
>  File "eval_psl.py", line 27, in <module>
>    from pycocotools.coco import COCO
>  File "/home/daisuke/MobilePose-pytorch/pycocotools/coco.py", line 55, in <module>
>    from . import mask as maskUtils
>  File "/home/daisuke/MobilePose-pytorch/pycocotools/mask.py", line 3, in <module>
>    import pycocotools._mask as _mask
>ImportError: /home/daisuke/MobilePose-pytorch/pycocotools/_mask.so: undefined symbol: rleEncode

Also, I noticed that I cannot reproduce 64bit one either. 
My 64 bit _make.so is quite smaller (original is 820kb, but mine is 256kb) and when I use it, I get same error above. (To create 64 bit _make.so, I used following command: `gcc -shared -fPIC _mask.c -o _mask.so`)

Could you tell me how did you create _make.so?
If you would tell it, I could reproduce 62bit version and prepare 32bit version by myself.

Thank you.

**Comment by Fangyh09** [comment]
This directory is forked from https://github.com/cocodataset/cocoapi.
You could follow the readme in this repo.

**Comment by ba-san** [comment]
thanks a lot!
