### ISSUE TITLE
Error in run_webcam 

### ISSUE THREAD

**Issue by ybclaire** [YuliangXiu/MobilePose-pytorch#21]
model=resnet18 --camera=0
Traceback (most recent call last):
  File "run_webcam.py", line 41, in <module>
    w, h = model_wh(get_graph_path(args.model))
NameError: name 'model_wh' is not defined
I can't find get_graph_path() either

Then I change the code to be like this:
    # load the model 
    # w, h = model_wh(get_graph_path(args.model)) # w,h not used
    modelpath = "./models/resnet18_224_sgd_best.t7" #this is the model I generated using training.py
    #e = ResEstimator(get_graph_path(args.model), target_size=(w,h))
    e = ResEstimator(modelpath, target_size=(224, 224))

Then I got an error:
Traceback (most recent call last):
  File "run_webcam.py", line 44, in <module>
    e = ResEstimator(modelpath, target_size=(224, 224))
  File "/home/ychen/MobilePose-pytorch-master/estimator.py", line 30, in __init__
    self.net.eval()
AttributeError: 'collections.OrderedDict' object has no attribute 'eval'

**Comment by YuliangXiu** [comment]
I updated the code, you can have a try on the new version.
