### ISSUE TITLE
training code not working

### ISSUE THREAD

**Issue by MetaDev** [YuliangXiu/MobilePose-pytorch#24]
I think some of the files are from previous versions of the code base. 
When I run the training command I get 
"AttributeError: 'CoordRegressionNetwork' object has no attribute 'outsize'"
Would it be possible to push the newest version of the code?
Thanks

**Comment by YuliangXiu** [comment]
I update the new version, you can have a try. Good Luck

**Comment by MetaDev** [comment]
Thanks! Will let you know once I have tested it.
