### ISSUE TITLE
Vis result is far from correct

### ISSUE THREAD

**Issue by liuyu666-thu** [YuliangXiu/MobilePose-pytorch#25]
I run a rgb image for test using mobilenetv2 model and get totally incorrect visible result (though evaluation AP is good). 
I made some modifications in pose encode and decode parts in order to fit DSNTNN.
Anybody got good visible results?

**Comment by YuliangXiu** [comment]
I made some modifications on my code, now you can use the latest models(.t7) and see what happens.

And this is a single person pose estimator, which means you first need to crop the person from original image manually or with the help of other human detectors (e.g. YOLO, SSD, R-CNN and so on) but not directly use the original image (person is not located in the center region)
