### ISSUE TITLE
Pose published whether there is a person or not?

### ISSUE THREAD

**Issue by JayLSU** [YuliangXiu/MobilePose-pytorch#27]
Hi, first thanks for your awesome codes to implement such mobile-pose.  I just tried the code and run webcam demo. I found that even there is no people appeared in my webcam, the pose also will be estimated and published. I checked the net output, it is a tuple with two parts, the first one is keypoints location, another I didn't figure out (it is a 52*52 data array for each joint I think.). I have no idea how to only display keypoints as long as there is a people there. Thanks.

**Comment by YuliangXiu** [comment]
The second part is joint heatmap, maybe you can extract the joint score from heatmap and remove the joints with low score when doing visualization.
