### ISSUE TITLE
how to run "run_webcam.py" on gpu

### ISSUE THREAD

**Issue by km23630** [YuliangXiu/MobilePose-pytorch#28]
I changed ".to("cpu")" code to ".to("cuda")."
but it print below error and not work

RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'weight'

how i can run this code use gpu?
i really want your advice
thank you!

**Comment by km23630** [comment]
i solved this problem 

1. convert network to cuda
net = net.to('cuda')

2. convert network input tensor to cuda
keypoints = self.net(image.to("cuda"))

3. convert output tensor to cpu
keypoints = keypoints[0].detach().cpu().numpy()

**Comment by YuliangXiu** [comment]
thanks for your solution.

**Comment by km23630** [comment]
ㄴ
