### ISSUE TITLE
gpu usage is very low

### ISSUE THREAD

**Issue by km23630** [YuliangXiu/MobilePose-pytorch#29]
#28 
After completing the steps above, gpu usage is very low
it this a cpu bottleneck?
i want a extreme speed Beyond real-time

on my gpu(1080ti) it's only 45 fps.
gpu usage is 4~5%, vram usage is 500mb

**Comment by YuliangXiu** [comment]
Maybe you can try the smaller model like SqueezeNet and read frames in batch, the current implementation is 1 batch size, which will cause the low gpu usage.

**Comment by km23630** [comment]
> Maybe you can try the smaller model like SqueezeNet and read frames in batch, the current implementation is 1 batch size, which will cause the low gpu usage.

thank you for fast reply
you mean, if i input batch for network, improve speed, right?

**Comment by km23630** [comment]
also i want skip  uncertain pose like "https://ibb.co/C1VCX0r"
can I skip uncertain pose on code?

**Comment by km23630** [comment]
> Maybe you can try the smaller model like SqueezeNet and read frames in batch, the current implementation is 1 batch size, which will cause the low gpu usage.

also i want skip uncertain pose like "https://ibb.co/C1VCX0r"
can I skip uncertain pose on code?

**Comment by YuliangXiu** [comment]
you can extract the pose score from heatmap and then delete the low-score keypoint when visualization.

**Comment by km23630** [comment]
> you can extract the pose score from heatmap and then delete the low-score keypoint when visualization.

thank you for your answer
