### ISSUE TITLE
I want to know heatmap value's range

### ISSUE THREAD

**Issue by km23630** [YuliangXiu/MobilePose-pytorch#31]
I want change heat map range to 0~255 for heatmap visualization.

I guessed heatmap range is 0~1 and tried multiply 255, but it was not.
When multiplied by 255, the heatmap's maximum value was about 30.

pleas let me know about heatmap value's range!

**Comment by YuliangXiu** [comment]
Yon can calculate the max-value and min-value from multi channels of heatmap. I think it is 0~1 after sigmoid function

**Comment by km23630** [comment]
> Yon can calculate the max-value and min-value from multi channels of heatmap. I think it is 0~1 after sigmoid function

unfortunately when I saw heatmap value its range is about 0.00000007 ~ 0.1
I can not set a threshold between joints and not joints.
In other words, I can't classify is person exist in image using heatmap

Thank you for your reply and I am sorry to bother you. 
:<

**Comment by YuliangXiu** [comment]
Maybe you should install the latest version of dsntnn. This kind of error has not occurred to me before.

**Comment by km23630** [comment]
> Maybe you should install the latest version of dsntnn. This kind of error has not occurred to me before.

ok I will try it

**Comment by km23630** [comment]
> Maybe you should install the latest version of dsntnn. This kind of error has not occurred to me before.

my dsntnn already 1.0.1

**Comment by YuliangXiu** [comment]
can you visualize some heatmap results to me
```

plt.imshow(heatmaps[0, 8].data.cpu().numpy())
plt.show()
```

**Comment by km23630** [comment]
this is my heatmap result.
text is maximum value in each heatmap

![cap](https://user-images.githubusercontent.com/30399899/56790151-c2fafb00-683e-11e9-8927-674483764483.PNG)

**Comment by YuliangXiu** [comment]
according to the visualization results, i think you can use a threshold to filter the low-score keypoint
