### ISSUE TITLE
resulted keypoints are not on right positions.

### ISSUE THREAD

**Issue by musab1234** [YuliangXiu/MobilePose-pytorch#34]
i am running `run_webcam.py` and its giving me correct and accurate output on different images but resulted skeleton is rotated at angle. i think its related to `pose_fun` lambda function in `estimator.py` which is running after image inference.  I have tried different models but same result. Currently i am using resnet18. Thank you

![image](https://user-images.githubusercontent.com/8913078/60489118-0188b800-9cbd-11e9-8827-8ee2f036dd7e.png)

**Comment by Fangyh09** [comment]
Hi, I think x and y are swapped.
You can try `keypoint = keypoint[:,::-1] ` after this line
https://github.com/YuliangXiu/MobilePose-pytorch/blob/3a64e58990cfca24b99bb1113d0f6accc2441325/estimator.py#L70

**Comment by musab1234** [comment]
Thank @Fangyh09 , yeah orientations has been fixed now ( by your code snippet) but skeleton is little bit translated to right.

![image](https://user-images.githubusercontent.com/8913078/60492362-4106d280-9cc4-11e9-822c-33909616ca18.png)

**Comment by Fangyh09** [comment]
I think it needs a vertical flip.
This image is not good to judge, could you try another image which is not so symmetrical?

**Comment by musab1234** [comment]
i have swapped points from bottom to top and swapped columns too 

```
keypoints = keypoints[:,::-1]
keypoints = keypoints[::-1,:]
```
by swaping columns result got more better but same issue with other images too.

![test3](https://user-images.githubusercontent.com/8913078/60498006-4584b880-9ccf-11e9-97ad-5768767cbd16.jpg)

**Comment by Fangyh09** [comment]
https://github.com/YuliangXiu/MobilePose-pytorch/blob/c5abac58ab24d275618d996aff4edbfe32e8c75a/estimator.py#L75

Yeah, I think the above line is not right. You can try to replace it by:
```python
ori_x = ((x + 1) * self.output_size - 1) / 2.0
pose_fun = lambda x: ((ori_x-[left_pad, top_pad]) * 1.0 /np.array([new_w, new_h])*np.array([w,h]))
```
