### ISSUE TITLE
倘若关节点不在检测框内，如何得到该坐标？

### ISSUE THREAD

**Issue by liuchanfeng165** [YuliangXiu/MobilePose-pytorch#37]
训练过程中不存在图中的关节点（如某部位不在框内或者被遮挡了），热点图不存在该位置响应，进入F运算后（0，0），得到是中心点，显然是不对的，作者有解决方法吗？

**Comment by YuliangXiu** [comment]
you can set a score threshold, if the keypoint score < threshold, just remove it.

**Comment by liuchanfeng165** [comment]
ok
