### ISSUE TITLE
what's your purpose of using Expansion()

### ISSUE THREAD

**Issue by GarrickLin** [YuliangXiu/MobilePose-pytorch#4]
I saw your data augmentation using Expansion by append two `meshgrid` channels, what is the purpose ?

**Comment by GarrickLin** [comment]
I'm not sure it make sense ?

**Comment by YuliangXiu** [comment]
This is a kind of engineering trick in improving regression performance, apart from original 3 RGB channels, we add X and Y channel, both of them are (h, w, 1) matrix. According to our final results, we find this trick works, although not too much. You can find the definition of **Expansion** in [dataloader.py](https://github.com/YuliangXiu/MobilePose-pytorch/blob/92ad2add5339d3e6bdae50c0bf49a617e8d7c466/dataloader.py#L109)

**Comment by agxcul** [comment]
> add two new dimension (R,G,B,X,Y)，X Y means the pixel position

can it be regarded as some kind of position encoding?

**Comment by YuliangXiu** [comment]
yes, you can regard it as position (xy coords) encoding
