### ISSUE TITLE
How to transplant to the mobile?

### ISSUE THREAD

**Issue by TwT520Ly** [YuliangXiu/MobilePose-pytorch#8]
Before i want to transplant the openpose to the mobile used mobileNet-V1 and tensorflow, then i train the model and get the pb file.But only can use the file in android to get the paf and heatmap,so i have to use java to implement it where connects the joint. So if i want to use python, cant you tell some advice?

**Comment by YuliangXiu** [comment]
Although this project was initially designed for the mobile device, I have not finished the Android/iOS support by now. I am working on supporting multi-person mode recently. 
I do not think the mobile device can support python well, so if you are not very hurry, you can wait for my multi-person version, which directly outputs multi-person keypoints.(no need to connect joints with PAF)

**Comment by Zeit42** [comment]
Will mobile support also be available for Raspberry Pi/Android Things?
