### ISSUE TITLE
where can I found the pre-trained model? Can you upload your final-trained model?

### ISSUE THREAD

**Issue by JackHenry1992** [YuliangXiu/MobilePose-pytorch#9]
Thanks for sharing your great work!
I have not found your pre-trained model, can you upload your well-trained model?

**Comment by YuliangXiu** [comment]
Because of some complicated reasons, I can not upload pretrained model now. But retrain the whole network is pretty fast, you can add `retrain=True` while training and get decent performance in few hours. Some friends(in issues) have already finished it and get applicable results. Good luck to you!
